sudo: required
dist: trusty
language: python
python:
  - "3.5"
jobs:
  include:
    - stage: first
      name: "Trigger rebuild of susi installer"
      jdk: oraclejdk8
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ (($TRAVIS_BRANCH == development) || ($TRAVIS_BRANCH == master)) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
          sh trigger-travis.sh fossasia susi_installer $TRAVIS_ACCESS_TOKEN
        fi
    - stage: first # runs in parallel with the previous job
      script: |
        sudo apt-get update --fix-missing
        # We are going to install realpath, which comes as a separate package in Ubuntu Trusty
        sudo apt-get install realpath
        chmod +x .travis_scripts/install.sh
        ./.travis_scripts/install.sh
        pip3 install -U pytest
        pip3 install -U pep8
    - stage: test # runs after the first stop has finished
      script: |
        pep8 main --ignore E501 --exclude=main/hotword_engine/snowboy_detector.py
        python3 -m pytest tests/
